### PR TITLE
uploaded to debian

### PR DESCRIPTION
**Pull request by eighthave**
I uploaded your package to Debian, thanks for packaging it!  I found it here:
http://mentors.debian.net/package/yubico-piv-tool

also, you should fetch my signed tag and push it to the official git repo.

### CODE REVIEW

**Comment by eighthave** [comment]
And for those who want Ubuntu packages, I uploaded this package to my PPA:
https://launchpad.net/~guardianproject/+archive/ubuntu/ppa/+packages

**Comment by jas4711** [comment]
Thank you!

Do you want to be added to Uploaders as well?

**Comment by eighthave** [comment]
No, I can't commit to maintaining this package, this was a drive by.  :-)  I was looking for a package for yubico-piv-tool, and found yours on mentors.debian.net.

**Comment by jas4711** [comment]
Ok thank you for the help!  We'll maintain it going forward (I became DD recently).

**Pull request merged**
