### PR TITLE
Baloo/newupstream 1.3.1

### PR DESCRIPTION
**Pull request by baloo**

### CODE REVIEW

**Comment by baloo** [comment]
I tried to respect the hierarchy of commits in my branch (as you may see in https://github.com/baloo/yubico-piv-tool-dpkg/network) but this will probably get fucked up by github pull requests and flatten out.

Please take care.

**Comment by baloo** [comment]
You may want to consider following commands to keep hierarchy:

```
git remote add baloo git@github.com:baloo/yubico-piv-tool-dpkg.git
git fetch baloo baloo/newupstream-1.3.1
git checkout master
git reset --hard baloo/baloo/newupstream-1.3.1
```

but I know reset is ugly.

**Comment by klali** [comment]
Are you preparing this as a NMU? In that case happy to merge it, otherwise I fear that it might be a bit of a mess to merge this if someone else does the upload.

**Comment by baloo** [comment]
Hi,

The nmu shouldn't have made to this pull request, I used it to generate a package for a simple repository (http://baloo.github.io/yubico-piv-tool-dpkg/ / https://github.com/baloo/yubico-piv-tool-dpkg/blob/github-repo/debian/rules#L22). I will rewrite that. 

I'm not a debian dev at all, I just happen to make debian package for my personal use :).

**Comment by klali** [comment]
I just imported 1.4.0, sorry for not getting back to you earlier.

**Comment by baloo** [comment]
no worries :) thanks :)

**Pull request closed without merging**
